name: Test dbt-risingwave

on: [push]

jobs:
  test-with-jaffle_shop:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Clone jaffle_shop
      run: git clone --depth 1 https://github.com/dbt-labs/jaffle_shop.git
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        jaffle_shop:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install dbt-risingwave globally
      run: python3 -m pip install .
      
    - name: dbt-seed
      run: dbt seed
      working-directory: jaffle_shop
      
    - name: dbt-run
      run: dbt run
      working-directory: jaffle_shop

    - name: dbt-doc
      run: dbt docs generate
      working-directory: jaffle_shop
  test-dbt_rw_nexmark:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566
        options: >-
          --add-host=host.docker.internal:host-gateway

    env:
      JS_UDF_HTTP_BIND_HOST: 0.0.0.0
      JS_UDF_HTTP_BASE_URL: http://host.docker.internal:18080
      PY_UDF_SERVER_BIND_HOST: 0.0.0.0
      PY_UDF_SERVER_URL: http://host.docker.internal:8815

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Clone dbt_rw_nexmark
      run: git clone --depth 1 https://github.com/risingwavelabs/dbt_rw_nexmark.git
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_rw_nexmark:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install dbt-risingwave globally
      run: |
        python3 -m pip install .
        python3 -m pip install -r dbt_rw_nexmark/scripts/python_udf_server_requirements.txt

    - name: Start UDF mock servers
      run: |
        python3 dbt_rw_nexmark/scripts/js_udf_http_server.py > /tmp/js_udf_http_server.log 2>&1 &
        python3 dbt_rw_nexmark/scripts/python_udf_server.py > /tmp/python_udf_server.log 2>&1 &
        timeout 30 bash -c 'until nc -z 127.0.0.1 18080; do sleep 1; done'
        timeout 30 bash -c 'until nc -z 127.0.0.1 8815; do sleep 1; done'

    - name: dbt-build
      run: dbt build
      working-directory: dbt_rw_nexmark

    - name: dbt-doc
      run: dbt docs generate
      working-directory: dbt_rw_nexmark

  test-basic-models:
    runs-on: ubuntu-latest
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_risingwave_basic_models:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install current adapter
      run: python3 -m pip install .
    - name: Wait for RisingWave to be ready
      run: timeout 60 bash -c 'until nc -z 127.0.0.1 4566; do sleep 1; done'
    - name: dbt-run
      run: dbt run --full-refresh
      working-directory: tests/e2e/basic_models
    - name: dbt-test
      run: dbt test
      working-directory: tests/e2e/basic_models
    - name: dbt-doc
      run: dbt docs generate
      working-directory: tests/e2e/basic_models

  test-table-with-connector:
    runs-on: ubuntu-latest
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_risingwave_table_with_connector:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install current adapter
      run: python3 -m pip install .
    - name: Wait for RisingWave to be ready
      run: timeout 60 bash -c 'until nc -z 127.0.0.1 4566; do sleep 1; done'
    - name: dbt-run-create
      run: dbt run --full-refresh
      working-directory: tests/e2e/table_with_connector
    - name: dbt-test-created-schema
      run: dbt test
      working-directory: tests/e2e/table_with_connector
    - name: dbt-run-existing-relation
      run: dbt run
      working-directory: tests/e2e/table_with_connector
    - name: dbt-test-existing-relation
      run: dbt test
      working-directory: tests/e2e/table_with_connector
    - name: insert-pre-evolution-row
      run: dbt run-operation insert_pre_evolution_row
      working-directory: tests/e2e/table_with_connector
    - name: dbt-run-additive-columns
      run: dbt run
      working-directory: tests/e2e/table_with_connector
      env:
        DBT_RW_TWC_ADD_EXTRA: "true"
    - name: dbt-test-additive-columns
      run: dbt test
      working-directory: tests/e2e/table_with_connector
      env:
        DBT_RW_TWC_EXPECT_EXTRA: "true"
    - name: dbt-doc
      run: dbt docs generate
      working-directory: tests/e2e/table_with_connector
      env:
        DBT_RW_TWC_ADD_EXTRA: "true"

  test-sinks:
    runs-on: ubuntu-latest
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_risingwave_sinks:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install current adapter
      run: python3 -m pip install .
    - name: Wait for RisingWave to be ready
      run: timeout 60 bash -c 'until nc -z 127.0.0.1 4566; do sleep 1; done'
    - name: dbt-run
      run: dbt run --full-refresh
      working-directory: tests/e2e/sinks
    - name: dbt-test
      run: dbt test
      working-directory: tests/e2e/sinks
    - name: dbt-run-existing-relations
      run: dbt run
      working-directory: tests/e2e/sinks
    - name: dbt-test-existing-relations
      run: dbt test
      working-directory: tests/e2e/sinks
    - name: dbt-doc
      run: dbt docs generate
      working-directory: tests/e2e/sinks

  test-incremental:
    runs-on: ubuntu-latest
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_risingwave_incremental:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install current adapter
      run: python3 -m pip install .
    - name: Wait for RisingWave to be ready
      run: timeout 60 bash -c 'until nc -z 127.0.0.1 4566; do sleep 1; done'
    - name: setup-initial-source
      run: dbt run-operation setup_initial_incremental_source
      working-directory: tests/e2e/incremental
    - name: dbt-run-initial
      run: dbt run --full-refresh
      working-directory: tests/e2e/incremental
    - name: dbt-test-initial
      run: dbt test
      working-directory: tests/e2e/incremental
      env:
        DBT_RW_INCREMENTAL_EXPECT_STAGE: initial
    - name: append-incremental-source
      run: dbt run-operation append_incremental_source
      working-directory: tests/e2e/incremental
    - name: dbt-run-incremental
      run: dbt run
      working-directory: tests/e2e/incremental
    - name: dbt-test-incremental
      run: dbt test
      working-directory: tests/e2e/incremental
      env:
        DBT_RW_INCREMENTAL_EXPECT_STAGE: incremental
    - name: reset-source-for-full-refresh
      run: dbt run-operation reset_incremental_source_for_full_refresh
      working-directory: tests/e2e/incremental
    - name: dbt-run-full-refresh
      run: dbt run --full-refresh
      working-directory: tests/e2e/incremental
    - name: dbt-test-full-refresh
      run: dbt test
      working-directory: tests/e2e/incremental
      env:
        DBT_RW_INCREMENTAL_EXPECT_STAGE: full_refresh
    - name: dbt-doc
      run: dbt docs generate
      working-directory: tests/e2e/incremental

  test-contracts:
    runs-on: ubuntu-latest
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_risingwave_contracts:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install current adapter
      run: python3 -m pip install .
    - name: Wait for RisingWave to be ready
      run: timeout 60 bash -c 'until nc -z 127.0.0.1 4566; do sleep 1; done'
    - name: dbt-run-contracts
      run: dbt run --full-refresh --select path:models/positive
      working-directory: tests/e2e/contracts
    - name: dbt-test-contracts
      run: dbt test
      working-directory: tests/e2e/contracts
    - name: dbt-run-bad-contract
      run: |
        if dbt run --select path:models/negative; then
          echo "bad contract model unexpectedly succeeded"
          exit 1
        fi
      working-directory: tests/e2e/contracts
    - name: dbt-doc
      run: dbt docs generate
      working-directory: tests/e2e/contracts

  test-store-failures:
    runs-on: ubuntu-latest
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_risingwave_store_failures:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install current adapter
      run: python3 -m pip install .
    - name: Wait for RisingWave to be ready
      run: timeout 60 bash -c 'until nc -z 127.0.0.1 4566; do sleep 1; done'
    - name: dbt-run
      run: dbt run --full-refresh
      working-directory: tests/e2e/store_failures
    - name: dbt-test-store-failures
      run: |
        if dbt test --select store_failures_persisted; then
          echo "store_failures_persisted unexpectedly succeeded"
          exit 1
        fi
      working-directory: tests/e2e/store_failures
    - name: assert-store-failures
      run: dbt run-operation assert_store_failures_results
      working-directory: tests/e2e/store_failures

  test-indexes:
    runs-on: ubuntu-latest
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_risingwave_indexes:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install current adapter
      run: python3 -m pip install .
    - name: Wait for RisingWave to be ready
      run: timeout 60 bash -c 'until nc -z 127.0.0.1 4566; do sleep 1; done'
    - name: dbt-run-initial-index
      run: dbt run --full-refresh
      working-directory: tests/e2e/indexes
      env:
        DBT_RW_INDEX_STAGE: initial
    - name: dbt-test-initial-index
      run: dbt test
      working-directory: tests/e2e/indexes
      env:
        DBT_RW_INDEX_EXPECT_STAGE: initial
    - name: dbt-run-apply-index-change
      run: dbt run
      working-directory: tests/e2e/indexes
      env:
        DBT_RW_INDEX_STAGE: changed
    - name: dbt-test-changed-index
      run: dbt test
      working-directory: tests/e2e/indexes
      env:
        DBT_RW_INDEX_EXPECT_STAGE: changed
    - name: dbt-doc
      run: dbt docs generate
      working-directory: tests/e2e/indexes
      env:
        DBT_RW_INDEX_STAGE: changed

  test-zero-downtime:
    runs-on: ubuntu-latest
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_risingwave_zero_downtime:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install current adapter
      run: python3 -m pip install .
    - name: Wait for RisingWave to be ready
      run: timeout 60 bash -c 'until nc -z 127.0.0.1 4566; do sleep 1; done'
    - name: dbt-run-initial
      run: dbt run --full-refresh
      working-directory: tests/e2e/zero_downtime
      env:
        DBT_RW_ZERO_DOWNTIME_STAGE: initial
    - name: dbt-test-initial
      run: dbt test
      working-directory: tests/e2e/zero_downtime
      env:
        DBT_RW_ZERO_DOWNTIME_EXPECT_STAGE: initial
    - name: dbt-run-zero-downtime-swap
      run: "dbt run --vars '{zero_downtime: true}'"
      working-directory: tests/e2e/zero_downtime
      env:
        DBT_RW_ZERO_DOWNTIME_STAGE: changed
    - name: dbt-test-zero-downtime-swap
      run: dbt test
      working-directory: tests/e2e/zero_downtime
      env:
        DBT_RW_ZERO_DOWNTIME_EXPECT_STAGE: changed
    - name: dbt-doc
      run: dbt docs generate
      working-directory: tests/e2e/zero_downtime
      env:
        DBT_RW_ZERO_DOWNTIME_STAGE: changed

  test-functions:
    runs-on: ubuntu-latest
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566
        options: >-
          --add-host=host.docker.internal:host-gateway

    env:
      JS_UDF_HTTP_BIND_HOST: 0.0.0.0
      JS_UDF_HTTP_BASE_URL: http://host.docker.internal:18080
      PY_UDF_SERVER_BIND_HOST: 0.0.0.0
      PY_UDF_SERVER_URL: http://host.docker.internal:8815

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_risingwave_functions:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install current adapter
      run: |
        python3 -m pip install .
        python3 -m pip install -r tests/e2e/functions/scripts/python_udf_server_requirements.txt
    - name: Start UDF mock servers
      run: |
        python3 tests/e2e/functions/scripts/js_udf_http_server.py > /tmp/js_udf_http_server.log 2>&1 &
        python3 tests/e2e/functions/scripts/python_udf_server.py > /tmp/python_udf_server.log 2>&1 &
        timeout 30 bash -c 'until nc -z 127.0.0.1 18080; do sleep 1; done'
        timeout 30 bash -c 'until nc -z 127.0.0.1 8815; do sleep 1; done'
    - name: Wait for RisingWave to be ready
      run: timeout 60 bash -c 'until nc -z 127.0.0.1 4566; do sleep 1; done'
    - name: dbt-build
      run: dbt build
      working-directory: tests/e2e/functions
    - name: dbt-run-existing-functions
      run: dbt run
      working-directory: tests/e2e/functions
    - name: dbt-test-existing-functions
      run: dbt test
      working-directory: tests/e2e/functions
    - name: dbt-doc
      run: dbt docs generate
      working-directory: tests/e2e/functions

  test-grants-docs-schema:
    runs-on: ubuntu-latest
    env:
      DBT_RW_SCHEMA_REGISTRY_URL: http://host.docker.internal:18081
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566
        options: >-
          --add-host=host.docker.internal:host-gateway

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_risingwave_grants_docs_schema:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: dbt_e2e_grants_docs_schema
              schema: dbt_e2e_grants_docs_schema
          target: dev
        EOF
    - name: Install current adapter
      run: python3 -m pip install .
    - name: Wait for RisingWave to be ready
      run: timeout 60 bash -c 'until nc -z 127.0.0.1 4566; do sleep 1; done'
    - name: prepare-roles-and-schema
      run: dbt run-operation prepare_grants_docs_schema
      working-directory: tests/e2e/grants_docs_schema
    - name: dbt-run
      run: dbt run --full-refresh
      working-directory: tests/e2e/grants_docs_schema
    - name: dbt-test
      run: dbt test
      working-directory: tests/e2e/grants_docs_schema
    - name: dbt-run-existing-relations
      run: dbt run
      working-directory: tests/e2e/grants_docs_schema
    - name: dbt-test-existing-relations
      run: dbt test
      working-directory: tests/e2e/grants_docs_schema
    - name: dbt-doc
      run: dbt docs generate
      working-directory: tests/e2e/grants_docs_schema

  test-source-connection:
    runs-on: ubuntu-latest
    env:
      DBT_RW_SCHEMA_REGISTRY_URL: http://host.docker.internal:18081
    services:
      risingwave:
        image: ghcr.io/risingwavelabs/risingwave:latest # RW version should be manually updated until a released version is compatiable with this adapter.
        ports:
          - 4566:4566
        options: >-
          --add-host=host.docker.internal:host-gateway

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup dbt profile
      run: |
        mkdir -p $HOME/.dbt && cat >> $HOME/.dbt/profiles.yml <<EOF
        dbt_risingwave_source_connection:
          outputs:
            dev:
              type: risingwave
              host: 127.0.0.1
              user: root
              pass: ""
              dbname: dev
              port: 4566
              schema: public
          target: dev
        EOF
    - name: Install current adapter
      run: python3 -m pip install .
    - name: Wait for RisingWave to be ready
      run: timeout 60 bash -c 'until nc -z 127.0.0.1 4566; do sleep 1; done'
    - name: dbt-source-connection-e2e
      run: |
        python3 scripts/mock_schema_registry.py > /tmp/mock_schema_registry.log 2>&1 &
        mock_schema_registry_pid=$!
        trap 'kill $mock_schema_registry_pid >/dev/null 2>&1 || true' EXIT
        timeout 30 bash -c 'until nc -z 127.0.0.1 18081; do sleep 1; done'
        dbt run --full-refresh
        dbt test
        dbt run
        dbt test
        dbt docs generate
      working-directory: tests/e2e/source_connection
